- hosts: all
  tasks:
    - name: debug all
      debug:
        msg: "--------------zuul {{ zuul }} -----------------"
      environment: '{{ global_env }}'

    - name: debug
      debug:
        msg: "This item is project: {{ item.project }}, change: {{ item.change }}, patchset: {{ item.patchset }}, job: {{ item.job }}, name: {{ item.name }}, url: {{ item.url }}, metadata: {{ item.metadata }}"
      vars:
        whl_file_name: "{{ item.name }}"
        whl_url: "{{ item.url }}"
      with_items: "{{ zuul.artifacts.values() | list }}"
      environment: '{{ global_env }}'

    - name: Return artifact to Zuul on version 1.15.3
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "{{ whl_file_name }}"
                url: "{{ whl_url }}"
      when:
        - item.metadata.version in ['1.15.3', '1.15.3l']
        - global_env.VERSION in ['1.15.3', '1.15.3l']
      loops: "{{ zuul.artifacts }}"
      environment: '{{ global_env }}'

    - name: Return artifact to Zuul on version 2.2.0
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "{{ whl_file_name }}"
                url: "{{ whl_url }}"
      when:
        - item.metadata.version in ['2.2.0']
        - global_env.VERSION in ['2.2.0']
      loops: "{{ zuul.artifacts }}"
      environment: '{{ global_env }}'
