- hosts: all
  tasks:
    - name: debug all
      debug:
        msg: "--------------zuul {{ zuul }} -----------------"
      environment: '{{ global_env }}'

    - name: artifact to Zuul on version 1.15.3
      loop: "{{ zuul.artifacts }}"
      when:
        - item.metadata.version in ['1.15.3', '1.15.3l']
        - global_env.VERSION in ['1.15.3', '1.15.3l']
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "{{ item.name }}"
                url: "{{ item.url }}"
      environment: '{{ global_env }}'

    - name: artifact to Zuul on version 2.2.0
      loop: "{{ zuul.artifacts }}"
      when:
        - item.metadata.version in ['2.2.0']
        - global_env.VERSION in ['2.2.0']
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "{{ item.name }}"
                url: "{{ item.url }}"
      environment: '{{ global_env }}'
