---
- name: Install and config golang
  include_role:
    name: config-golang

- name: Install master of Packer from source
  shell: |
    set -ex
    cd ../../
    mv liu-sheng hashicorp
    cd hashicorp/packer
    sleep 72000
    make dev
    packer version
  environment: '{{ global_env }}'
  args:
    executable: /bin/bash
    chdir: '{{ zuul.project.src_dir }}'
