- hosts: all
  become: yes
  roles:
    - install-openjdk
    - install-maven
  tasks:
    - name: install required packages
      shell: |
        set -exo pipefail

        # Workaroud: the "com.google.protobuf:protoc:2.5.0" for ARM64 release does not exit in Maven central repo
        # sed -i 's|com.google.protobuf:protoc:2.5.0|com.github.os72:protoc:2.6.1-build3|g' `grep "protoc:2.5.0" -rl ./`
        # git diff

        mvn -B -e clean package -Pdist -DskipTests 2>&1 | tee "{{ ansible_user_dir }}/workspace/logs/hive_build.log"
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
