- hosts: all
  become: yes
  roles:
  tasks:
    - name: install required packages
      shell: |
        apt-get update -y

        # install java
        apt-get install default-jre -y
        apt-get install default-jdk -y
        echo "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-arm64" >> ~/.profile
        # echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.profile
        echo "export PATH=$PATH:$JAVA_HOME/bin" >> ~/.profile
        source ~/.profile

        # install mvn
        apt-get install maven -y
        mvn --version

        # install dependencies for protobuf build
        apt-get install autoconf automake libtool -y
        sleep 72000

        # Fix protobuf-2.5.0
        cd /usr/local/src/
        wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
        wget -O protobuf-2.5.0-arm64.patch https://www.dropbox.com/s/713wql5cw9dfxhx/protobuf-2.5.0-arm64.patch?dl=0
        tar xfz protobuf-2.5.0.tar.gz
        cd protobuf-2.5.0
        patch -p1 < ../protobuf-2.5.0-arm64.patch
        apt-get install build-essential
        apt-get install automake libtool autoconf
        ./autogen.sh
        ./configure --prefix=/usr
        make
        make install
        ldconfig
        protoc --version

        cd '{{ ansible_user_dir }}/workspace'
        git clone https://git-wip-us.apache.org/repos/asf/hive.git
        cd hive
        grep "protoc:2.5.0" ./* -R -l
        sed -i 's|<protocArtifact>com.google.protobuf:protoc:2.5.0</protocArtifact>|<protocExecutable>/usr/bin/protoc</protocExecutable>|g' ./standalone-metastore/metastore-common/pom.xml
        sed -i 's|<protocArtifact>com.google.protobuf:protoc:2.5.0</protocArtifact>|<protocExecutable>/usr/bin/protoc</protocExecutable>|g' ./standalone-metastore/metastore-server/pom.xml
        git diff

        mvn -e clean package -Pdist -DskipTests
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'