- hosts: all
  become: yes
  tasks:
  - name: Clean up remote repo resources
    shell:
      cmd: |
        apt install -y python-pip
        pip install pygithub

        cat > 'clean_repo_resource.py' <<EOF
        import github

        github_obj = github.Github('moo-ai', 'mooopenlab1')
        repo = github_obj.get_user().get_repo('moo-ai.github.io')
        try:
            pr = repo.get_pull(int({{ zuul.change }}))
        except github.UnknownObjectException:
            exit(0)

        branch_name = pr.head.ref
        pr.edit(state="closed")
        try:
            ref = repo.get_git_ref("heads/" + branch_name)
        except github.UnknownObjectException:
            exit(0)
        ref.delete()
        EOF

        python clean_repo_resource.py
      executable: /bin/bash
