- name: AI On Openlab Pre J
  hosts: all
  become: yes
  tasks:
    - name: Get User Metadata Zip or Url
      shell:
        cmd: |
          set -x
          set -e

          apt install -y unzip
          pip install pyyaml

          result_folder="{{ ansible_user_dir }}/workspace/test_results/"
          mkdir -p $result_folder

          user_data_folder='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
          cd $user_data_folder

          if ls | grep txt;then
            txt_file=`ls | grep txt`
            url=`cat $txt_file`
            wget $url
          fi

          zip_file=`ls | grep zip`

          unzip $zip_file
          python '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/tools/analysis_yaml.py'
        executable: /bin/bash

    - name: Get Runtime Info
      shell: cat '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/framework_runtime.txt'
      register: runtime

    - set_fact:
        runtime_name: "{{ runtime.stdout | regex_replace('[\d+\.*]+', '') }}"
        runtime_version: "{{ runtime.stdout | regex_replace('[java|go|python|c|c++]', '') }}"

    - name: Get Framework Name
      shell: cat '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/framework_name.txt'
      register: framework

    - name: Get Framework Version
      shell: cat {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/framework_version.txt'
      register: framework_version

    - name: Get User Entry Point
      shell: cat {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/entry_point.txt'
      register: entrypoint

    - name: Check output folder variable exists
      stat:
        path: '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/output_folder.txt'
      register: stat_ouput_folder_variable

    - name: Get output folder variable value
      when: stat_ouput_folder_variable.stat.exists
      shell: cat '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/output_folder.txt'
      register: output_folder_name

    - name: Check output folder exists
      stat:
        path: '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/{{ output_folder_name.stdout }}'
      register: stat_ouput_folder
